
version: "3.8"
services:
  docker-mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE= Mydrone
      - MYSQL_PASSWORD=root56789
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root56789
    ports:
      - 3307:3306

  app:
    build: .
    image: drone_server:latest
    ports:
      - 8080:8080
    environment:
      - DATABASE_USER= root
      - DATABASE_PASSWORD= root56789
      - DATABASE_NAME= Mydrone
      - DATABASE_PORT= 3306

    depends_on:
      - docker-mysql


